### ISSUE TITLE
xot v0.22.0 fails to compile on Rust 1.77.0

### ISSUE THREAD

**Issue by kawadakk** [faassen/xot#23]
```
error[E0309]: the parameter type `V` may not live long enough
   --> /home/$USER/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xot-0.22.0/src/nodemap/core.rs:100:9
    |
37  |   impl<'a, K, V, A: ValueAdapter<K, V>> NodeMap<'a, K, V, A>
    |        -- the parameter type `V` must be valid for the lifetime `'a` as defined here...
...
100 | /         self.iter_value()
101 | |             .map(|value| (A::key(value), A::value(value)))
    | |__________________________________________________________^ ...so that the type `V` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
40  |     V: Clone + 'a,
    |              ++++

error[E0309]: the parameter type `V` may not live long enough
   --> /home/$USER/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xot-0.22.0/src/nodemap/core.rs:116:9
    |
37  | impl<'a, K, V, A: ValueAdapter<K, V>> NodeMap<'a, K, V, A>
    |      -- the parameter type `V` must be valid for the lifetime `'a` as defined here...
...
116 |         self.iter_value().map(move |value| A::value(value))
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...so that the type `V` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound
    |
40  |     V: Clone + 'a,
    |              ++++

For more information about this error, try `rustc --explain E0309`.
error: could not compile `xot` (lib) due to 2 previous errors
```

<https://github.com/faassen/xot/blob/6fbd052674ad1e28136d07641828e063e9239779/src/nodemap/core.rs#L99-L102>

<https://github.com/faassen/xot/blob/6fbd052674ad1e28136d07641828e063e9239779/src/nodemap/core.rs#L115-L117>

**Comment by kawadakk** [comment]
This probably has been caused by <https://github.com/rust-lang/rust/pull/120019> (a soundness fix).

**Comment by faassen** [comment]
Thanks!  I've followed the suggestion and added a `'a` and after that it compiles again. I've made a new release, 0.23, which also has various changes and new features concerning serialization I still had to release.
